
source "arm" "autogenerated_1" {
  file_checksum_type    = "sha256"
  file_checksum_url     = "https://dl-cdn.alpinelinux.org/alpine/v3.14/releases/armhf/alpine-minirootfs-3.14.2-armhf.tar.gz.sha256"
  file_target_extension = "tar.gz"
  file_unarchive_cmd    = ["tar", "-xpf", "$ARCHIVE_PATH", "-C", "$MOUNTPOINT"]
  file_urls             = ["https://dl-cdn.alpinelinux.org/alpine/v3.14/releases/armhf/alpine-minirootfs-3.14.2-armhf.tar.gz"]
  image_build_method    = "new"
  image_chroot_env      = ["PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/sbin:/usr/sbin"]
  image_partitions {
    filesystem   = "ext4"
    mountpoint   = "/"
    name         = "root"
    size         = "0"
    start_sector = "4096"
    type         = "83"
  }
  image_path                   = "alpine-v2.img"
  image_size                   = "1G"
  image_type                   = "dos"
  qemu_binary_destination_path = "/usr/bin/qemu-arm-static"
  qemu_binary_source_path      = "/usr/bin/qemu-arm-static"
}


build {
  sources = ["source.arm.autogenerated_1"]

  provisioner "shell" {
    inline = [
      "echo 'nameserver 8.8.8.8' > /etc/resolv.conf",
      "apk update",
      "apk add alpine-conf nano",
      "/sbin/setup-alpine -q",
      ]
  }
}
